<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\TEDx.Domain\TEDx.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Identity\DTOs\" />
    <Folder Include="Identity\Command\" />
    <Folder Include="Identity\Queries\" />
    <Folder Include="Identity\Validators\" />
    <Folder Include="Ticketing\Command\" />
    <Folder Include="Ticketing\DTOs\" />
    <Folder Include="Ticketing\Queries\" />
    <Folder Include="Ticketing\Validators\" />
    <Folder Include="Training\Command\" />
    <Folder Include="Training\DTOs\" />
    <Folder Include="Training\Queries\" />
    <Folder Include="Training\Validators\" />
  </ItemGroup>

</Project>
