<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Eventing\Entities\" />
    <Folder Include="Eventing\Enums\" />
    <Folder Include="Eventing\Interfaces\" />
    <Folder Include="Eventing\ValueObjects\" />
    <Folder Include="Identity\Entities\" />
    <Folder Include="Identity\Enums\" />
    <Folder Include="Identity\Domain_Interfaces\" />
    <Folder Include="Identity\" />
    <Folder Include="Identity\ValueObjects\" />
    <Folder Include="Training\Entities\" />
    <Folder Include="Training\Enums\" />
    <Folder Include="Training\Interfaces\" />
    <Folder Include="Training\ValueObjects\" />
  </ItemGroup>

</Project>
