<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="Identity\ValueObjects\**" />
    <Compile Remove="Ticketing\ValueObjects\**" />
    <Compile Remove="Training\ValueObjects\**" />
    <EmbeddedResource Remove="Identity\ValueObjects\**" />
    <EmbeddedResource Remove="Ticketing\ValueObjects\**" />
    <EmbeddedResource Remove="Training\ValueObjects\**" />
    <None Remove="Identity\ValueObjects\**" />
    <None Remove="Ticketing\ValueObjects\**" />
    <None Remove="Training\ValueObjects\**" />
  </ItemGroup>
 
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>
</Project>
