<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Folder Include="Identity\ValueObjects\" />
    <Folder Include="Ticketing\ValueObjects\" />
    <Folder Include="Training\ValueObjects\" />
  </ItemGroup>
 
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>
</Project>
