<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TEDx.Domain\TEDx.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Eventing\Command\" />
    <Folder Include="Eventing\DTOs\" />
    <Folder Include="Eventing\Interfaces\" />
    <Folder Include="Eventing\Validators\" />
    <Folder Include="Eventing\Queries\" />
    <Folder Include="Identity\Command\" />
    <Folder Include="Identity\DTOs\" />
    <Folder Include="Identity\Interfaces\" />
    <Folder Include="Identity\Validators\" />
    <Folder Include="Identity\Queries\" />
    <Folder Include="Training\Command\" />
    <Folder Include="Training\DTOs\" />
    <Folder Include="Training\Interfaces\" />
    <Folder Include="Training\Validators\" />
    <Folder Include="Training\Queries\" />
  </ItemGroup>

</Project>
