<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TEDx.Application\TEDx.Application.csproj" />
    <ProjectReference Include="..\TEDx.Domain\TEDx.Domain.csproj" />
  </ItemGroup>

</Project>
